In [1]:
from random import randint
import numpy as np

In [2]:
def play_random(board):
    p = [i for i, v in enumerate(board) if v==0]
    return p[randint(0, len(p)-1)]

In [3]:
from random import randint
import numpy as np
board = [0,0,0,0,0,0,0,0,0]
lines = [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]]
win = 0

def checkWin(board, id):
    for l in lines:
        if board[l[0]]==id and board[l[1]]==id and board[l[2]]==id:
            return 1
    return 0

def myMove(board,n,t):
    global win
    if checkWin(board, n):
        ways = n
        for k in range(8-t,1,-1):
            ways*=k
        if t==turn:
            win=1
        return ways
    score = [0,0,0,0,0,0,0,0,0]
    for i in range(9):
        if board[i]==0:
            b = board[:]
            b[i]=-1*n
            score[i]=myMove(b,-1*n,t+1)
    return sum(score)

In [4]:
trainX = []
trainy = []

In [5]:
for cc in range(100):
    X = []
    y = []
    board = [0,0,0,0,0,0,0,0,0]
    lines = [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]]
    win = 0
    order = randint(0, 1)
    for turn in range(9):
        if win:
            break
        if turn%2 == order:
            # print np.array(board).reshape(3,3)
            # move = int(raw_input("Pick your position(1 to 9): "))
            move = play_random(board)
            board[move-1]=-1
        else:
            mscore = -10000000000
            mid = 0
            for i in range(9):
                if board[i]==0:
                    b = board[:]
                    b[i]=1
                    s = myMove(b,1,turn)
                    if s>mscore:
                        mscore=s
                        mid=i
            X.append(board[:])
            y.append(mid)
            board[mid]=1

    print np.array(board).reshape(3,3)
    if win:
        trainX.extend(X)
        trainy.extend(y)
        print("Computer Wins")
    else:
        print("It's a draw")

[[ 0 -1  1]
 [ 0  1  0]
 [-1  0  1]]
Computer Wins
[[ 1 -1  0]
 [ 1 -1  0]
 [ 1  0 -1]]
Computer Wins
[[-1  1 -1]
 [ 0  1 -1]
 [ 0  1  0]]
Computer Wins
[[ 1  1 -1]
 [ 1 -1  0]
 [-1  0  0]]
It's a draw
[[-1  1  1]
 [ 0  1  0]
 [ 0  0  0]]
Computer Wins
[[ 0  0  1]
 [ 1  1  0]
 [-1  1 -1]]
Computer Wins
[[ 1 -1  0]
 [ 0  1  0]
 [ 1 -1  0]]
Computer Wins
[[ 1  1  1]
 [ 0  1 -1]
 [-1 -1  0]]
Computer Wins
[[ 1  0  0]
 [-1  1  0]
 [-1 -1  1]]
Computer Wins
[[ 1  1  1]
 [ 0 -1 -1]
 [ 0 -1  0]]
Computer Wins
[[ 1  1  1]
 [ 0 -1  0]
 [-1 -1  0]]
Computer Wins
[[ 1  0 -1]
 [ 0  1 -1]
 [ 0  0  1]]
Computer Wins
[[-1  1  1]
 [ 1 -1  0]
 [-1  0  0]]
It's a draw
[[-1  1 -1]
 [ 0  1 -1]
 [ 0  1  0]]
Computer Wins
[[ 1  1 -1]
 [ 0  1 -1]
 [-1  0 -1]]
It's a draw
[[ 1  0  0]
 [ 1 -1 -1]
 [ 1 -1  0]]
Computer Wins
[[-1  1  1]
 [ 1 -1  0]
 [-1  0  1]]
Computer Wins
[[ 1 -1  0]
 [ 0  1 -1]
 [-1  0  1]]
Computer Wins
[[ 0  0  1]
 [ 0  1 -1]
 [ 1  0 -1]]
Computer Wins
[[-1  0  1]
 [ 0  1  0]
 [ 1 -1  0]]


In [7]:
from sklearn.tree import DecisionTreeClassifier
m = DecisionTreeClassifier()

In [8]:
m.fit(trainX,trainy)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [ ]:
from random import randint
import numpy as np
board = [0,0,0,0,0,0,0,0,0]
lines = [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]]
endgame = 0
win = 0

def checkWin(board, id):
    for l in lines:
        if board[l[0]]==id and board[l[1]]==id and board[l[2]]==id:
            return 1
    return 0

def myDTMove(board,n,t):
    mid = m.predict([board])
    mid = mid[0]
    if board[mid]==0:
        return mid
    else:
        print "Resorting to random"
        return play_random(board)

order = randint(0, 1)
# order = 0
for turn in range(0,9):
    if win:
        break
    if turn%2 == order:
        print np.array(board).reshape(3,3)
        move = int(raw_input("Pick your position(1 to 9): "))
        board[move-1]=-1
    else:
        mid = myDTMove(board,1,turn)
        board[mid]=1

print np.array(board).reshape(3,3)
if win:
    print("Computer Wins")
else:
    print("It's a draw")

[[0 0 0]
 [0 0 0]
 [0 0 0]]
Pick your position(1 to 9): 6
[[ 0  0  0]
 [ 0  1 -1]
 [ 0  0  0]]
Pick your position(1 to 9): 8
[[ 0  0  0]
 [ 0  1 -1]
 [ 0 -1  1]]
