In [1]:
from random import randint
import numpy as np
board = [0,0,0,0,0,0,0,0,0]
lines = [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]]
endgame = 0
win = 0

def check(l,n):
    if board[l[0]]==0 and board[l[1]]==n and board[l[2]]==n:
        return 0
    elif board[l[0]]==n and board[l[1]]==0 and board[l[2]]==n:
        return 1
    elif board[l[0]]==n and board[l[1]]==n and board[l[2]]==0:
        return 2
    else:
        return -1
    
def checkWin():
    for l in lines:
        r = check(l,1)
        if r>=0:
            board[l[r]]=1
            return 1
    return 0

def checkLoss():
    for l in lines:
        r = check(l,2)
        if r>=0:
            board[l[r]]=1
            return 1
    return 0

def openMove():
    if board[4]==0:
        board[4]=1
        return 1    
    for i in range(0,9,2):
        if board[i]==0:
            board[i]=1
            return 1
    for i in range(1,9,2):
        if board[i]==0:
            board[i]=1
            return 1
    
def play(turn):
    global win
    global endgame
    if checkWin():
        win=1
        return 1
    elif checkLoss():
        return 0
    elif turn==2 and (board[1] or board[3] or board[5] or board[7]):
        endgame=1
        if board[1] or board[7]:
            board[3]=1
        else:
            board[1]=1
    elif endgame:
        if board[1]==1:
            board[2]=1
        else:
            board[6]=1
    else:
        openMove()          
    return 0

order = randint(0, 1)
for turn in range(9):
    if turn%2 == order:
        print np.array(board).reshape(3,3)
        move = int(raw_input("Pick your position(1 to 9): "))
        board[move-1]=2
    else:
        if play(turn):
            break
print np.array(board).reshape(3,3)
if win:
    print("Computer Wins")
else:
    print("It's a draw")

[[0 0 0]
 [0 0 0]
 [0 0 0]]
Pick your position(1 to 9): 6
[[0 0 0]
 [0 1 2]
 [0 0 0]]
Pick your position(1 to 9): 8
[[1 0 0]
 [0 1 2]
 [0 2 0]]


KeyboardInterrupt: 

In [3]:
from random import randint
import numpy as np
board = [0,0,0,0,0,0,0,0,0]
lines = [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]]
endgame = 0
win = 0

def checkWin(board, id):
    for l in lines:
        if board[l[0]]==id and board[l[1]]==id and board[l[2]]==id:
            return 1
    return 0

def myMove(board,n,t):
    global win
    if checkWin(board, n):
        ways = n
        for k in range(8-t,1,-1):
            ways*=k
        if t==turn:
            win=1
        return ways
    score = [0,0,0,0,0,0,0,0,0]
    for i in range(9):
        if board[i]==0:
            b = board[:]
            b[i]=-1*n
            score[i]=myMove(b,-1*n,t+1)
    return sum(score)

order = 0
for turn in range(9):
    if win:
        break
    if turn%2 == order:
        print np.array(board).reshape(3,3)
        move = int(raw_input("Pick your position(1 to 9): "))
        board[move-1]=-1
    else:
        mscore = -10000000000
        mid = 0
        for i in range(9):
            if board[i]==0:
                b = board[:]
                b[i]=1
                s = myMove(b,1,turn)
                if s>mscore:
                    mscore=s
                    mid=i
        board[mid]=1

print np.array(board).reshape(3,3)
if win:
    print("Computer Wins")
else:
    print("It's a draw")

[[0 0 0]
 [0 0 0]
 [0 0 0]]
Pick your position(1 to 9): 1
[[-1  0  0]
 [ 0  1  0]
 [ 0  0  0]]
Pick your position(1 to 9): 8
[[-1  0  1]
 [ 0  1  0]
 [ 0 -1  0]]


KeyboardInterrupt: 

In [ ]:
from random import randint
import numpy as np
board = [0,0,0,0,0,0,0,0,0]
lines = [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]]
endgame = 0
win = 0

def checkWin(board, id):
    for l in lines:
        if board[l[0]]==id and board[l[1]]==id and board[l[2]]==id:
            return 1
    return 0

def myMove(board,n,t):
    if t==9:
        return 0, -1
    mscore = -10000000000
    mid = 0
    global win
    for i in range(9):
        if board[i]==0:
            b = board[:]
            b[i]=n
            if checkWin(b, n):
                ways = n
                for k in range(8-t,1,-1):
                    ways*=k
                if turn==t:
                    win=1
                return ways, i
            s,p = myMove(b,-1*n,t+1)
            if n*s>mscore:
                mscore=n*s
                mid=i
    return n*mscore, mid

order = randint(0, 1)
order = 1
for turn in range(0,9):
    if win:
        break
    if turn%2 == order:
        print np.array(board).reshape(3,3)
        move = int(raw_input("Pick your position(1 to 9): "))
        board[move-1]=-1
    else:
        s,mid = myMove(board,1,turn)
        board[mid]=1

print np.array(board).reshape(3,3)
if win:
    print("Computer Wins")
else:
    print("It's a draw")

[[1 0 0]
 [0 0 0]
 [0 0 0]]
