# Pair Problem #1

These problems involves first doing some math, either in your head or with pencil and paper, and only afterward verifying with Python.

For each problem, there is a matrix `X` and a vector `y`. You are looking for a vector `w` so that when you take a row of `X` and multiply each element by its corresponding element of `w` and then sum the results (the dot product of the row of `X` with `w`) you get the value at the corresponding position of `y`. For example, if we have:

```
X = [[5, 3, 7],   y = [537,
     [2, 4, 1]]        241]
```

A solution is `w = [100, 10, 1]`.

For each problem, answer two things:

 1. How many solutions are there? Why?
 2. If there are any solutions, what is one?

Problem A:

```
X = [[2]]        y = [8]
```

Problem B:

```
X = [[0]]        y = [8]
```

Problem C:

```
X = [[2, 4]]     y = [8]
```

Problem D:

```
X = [[2, 4],     y = [8,
     [0, 1]]          3]
```

Problem E:

```
X = [[2, 4],     y = [8,
     [0, 1],          3,
     [9, 5]]          1]
```

Problem F:

```
X = [[2, 2],     y = [4,
     [3, 3]]          6]
```

Problem G:

```
X = [[1, 1, 0],    y = [8,
     [1, 0, 1]]         6]
```

In [44]:
def solve(x, y):
    x, y = np.asarray(x), np.asarray(y)
    """Mimics `np.linalg.solve`, but does not require X be square."""
    b, *_ = np.linalg.lstsq(x, y)
    return b

In [45]:
x = [[2]]
y = [8]
solve(x, y)

array([ 4.])

In [46]:
x = [[0]]
y = [8]
solve(x, y)

array([ 0.])

In [47]:
x = [[2, 4]]
y = [8]
solve(x, y)

array([ 0.8,  1.6])

In [48]:
x = [[2, 4],
     [0, 1]]
y = [8, 3]
solve(x, y)

array([-2.,  3.])

# Pair Problem #2

The data for this problem are the numbers 2, 7, 1, 5, and 10.

We want to know which of the numbers from 0 to 10 (by tenths) gives the smallest result when we do the following:

For each of the numbers in the data, subtract the candidate number and then square the result, then add up these numbers.

For example, to test the candidate number 8.2, we do the following:

```
2 - 8.2 = -6.2
         (-6.2)**2 = 38.44
7 - 8.2 = -1.2
         (-1.2)**2 = 1.44
1 - 8.2 = -7.2
         (-7.2)**2 = 51.84
5 - 8.2 = -3.2
         (-3.2)**2 = 10.24
10 - 8.2 = 1.8
           1.8**2  = 3.24

38.44 + 1.44 + 51.84 + 10.24 + 3.24 = 105.2
```

In [3]:
def minimize(data, candidate):
    diff = data - candidate[:, None]
    idx = np.square(diff).sum(axis=1).argmin()
    return candidate[idx]

data = np.array([2, 7, 1, 5, 10], dtype=np.float_)
candidate = np.arange(0, 10.1, step=.1)

print(minimize(data, candidate))

5.0
