text = ["wookie stormtrooper",
        "wookie wookie wookie stormtrooper stormtrooper stormtrooper",
        "harry potter"]
Transform this data into a bag of words representation, with simple counts. How informative is this format? How much information do you have about individual words?
Calculate Euclidean and cosine distances between each pair of documents. How do these distances relate to your intuition for the documents' similarities?
Calculate one minus the cosine distance between each pair of de-meaned documents, and the Pearson correlation coefficient between each pair of documents. How are they related? Is this a coincidence? Find a counterexample or prove that there isn't one.


In [11]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

In [12]:
text = ["wookie stormtrooper",
        "wookie wookie wookie stormtrooper stormtrooper stormtrooper",
        "harry potter"]

In [13]:
vectorizer=CountVectorizer()
vectorizer.fit(text)
data=vectorizer.fit_transform(text)

In [14]:
cols=vectorizer.get_feature_names()
#cols

In [15]:
df=pd.DataFrame(data.toarray(),columns=cols)
df.head()

harry  potter  stormtrooper  wookie
0      0       0             1       1
1      0       0             3       3
2      1       1             0       0

In [16]:
import numpy as np
# Euclidean distance
def euclidean(x1,x2):
    data=zip(x1,x2)
    dist=np.sqrt(sum([(d[0]-d[1])**2 for d in data]))
    return dist

In [17]:
df.head()

harry  potter  stormtrooper  wookie
0      0       0             1       1
1      0       0             3       3
2      1       1             0       0

In [18]:
for i in range(len(df)):
    print('\n')
    print('for row %i')%i
    for j in range(len(df)):
        if i!=j:
            print(euclidean(df.iloc[i],df.iloc[j]))



for row 0
2.82842712475
2.0


for row 1
2.82842712475
4.472135955


for row 2
2.0
4.472135955


In [38]:
from sklearn.metrics.pairwise import pairwise_distances
print('euclidean')
print(pairwise_distances(df, metric='euclidean'))
print('\n')
print('cosine')
print(pairwise_distances(df, metric='cosine'))

euclidean
[[ 0.          2.82842712  2.        ]
 [ 2.82842712  0.          4.47213595]
 [ 2.          4.47213595  0.        ]]


cosine
[[ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 1.  1.  0.]]


In [39]:
# For euclidean: 'Distance' based on 'counts' (as opposed to words)

In [21]:
# Cos distance
def cosine(x1,x2):
    num=np.dot(x1,x2)
    # calculate magnitude of each vector
    den_x1=np.sqrt(np.sum([a**2 for a in x1]))
    den_x2=np.sqrt(np.sum([b**2 for b in x2]))
    cos=num/(den_x1*den_x2)
    return cos

In [22]:
df.head()

harry  potter  stormtrooper  wookie
0      0       0             1       1
1      0       0             3       3
2      1       1             0       0

In [23]:
for i in range(len(df)):
    print('\n')
    print('for row %i')%i
    for j in range(len(df)):
        if i!=j:
            print(cosine(df.iloc[i],df.iloc[j]))
            
# cos sim : for row 0 :  row 1 is perfectly similar and row 2 is
# exactly different ..
# really interested in orientation of our vector



for row 0
1.0
0.0


for row 1
1.0
0.0


for row 2
0.0
0.0


In [24]:
# Cos distance
def cosine_dist(x1,x2):
    num=np.dot(x1,x2)
    den_x1=np.sqrt(np.sum([a**2 for a in x1]))
    den_x2=np.sqrt(np.sum([b**2 for b in x2]))
    cos_dist=1- num/(den_x1*den_x2)
    return cos_dist

In [25]:
for i in range(len(df)):
    print('\n')
    print('for row %i')%i
    for j in range(len(df)):
        if i!=j:
            print(cosine_dist(df.iloc[i],df.iloc[j]))
    



for row 0
0.0
1.0


for row 1
0.0
1.0


for row 2
1.0
1.0


In [26]:
from sklearn.metrics.pairwise import pairwise_distances
dist=pairwise_distances(df,metric='cosine').round(2)
dist

array([[ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 1.,  1.,  0.]])

In [27]:
df.head()

harry  potter  stormtrooper  wookie
0      0       0             1       1
1      0       0             3       3
2      1       1             0       0

In [28]:
# Pearsons
df.mean(axis=1)

0    0.5
1    1.5
2    0.5
dtype: float64

In [29]:
centered= df.sub(df.mean(axis=1), axis=0)
centered.head()

harry  potter  stormtrooper  wookie
0   -0.5    -0.5           0.5     0.5
1   -1.5    -1.5           1.5     1.5
2    0.5     0.5          -0.5    -0.5

In [30]:
# How similar (taking into account typical row counts)

In [31]:
# Pearsons:
for i in range(len(df)):
    print('\n')
    print('for row %i')%i
    for j in range(len(centered)):
        if i!=j:
            print(cosine(centered.iloc[i],centered.iloc[j]))



for row 0
1.0
-1.0


for row 1
1.0
-1.0


for row 2
-1.0
-1.0


In [32]:
# Check if: numpy's pearson's coefficient? 
np.corrcoef(df)

array([[ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [-1., -1.,  1.]])

Pair Problem #2

Imagine a data matrix with three rows and two columns. Each row represents an observation, and each column represents a feature. (This is our usual convention.)

Imagine subtracting out the column means.

Imagine multiplying the transpose of this matrix by itself.

Don't just imagine it—write this out!

What familiar calculation is this? What result have you produced?

In [4]:
import pandas as pd
import numpy as np

In [5]:
data=pd.DataFrame({'a':[23,28,35],'p':[35,53,68]})
means=np.mean(data)
means

a    28.666667
p    52.000000
dtype: float64

In [6]:
zero_dt=data-means
zero_dt.head()

a     p
0 -5.666667 -17.0
1 -0.666667   1.0
2  6.333333  16.0

In [7]:
# covariance matrix
corr=np.dot(np.transpose(zero_dt),zero_dt)
corr

array([[  72.66666667,  197.        ],
       [ 197.        ,  546.        ]])